version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.8
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v2.52.0
    ports:
      - "9090:9090"
    volumes:
      - ./docker-volume-files/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - loki

  otel-collector:
    image: otel/opentelemetry-collector:0.101.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./docker-volume-files/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:2.4.2
    command: [ "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    ports:
      - "14250:14250"
      - "4317"
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:11.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./docker-volume-files/grafana/:/etc/grafana/provisioning/datasources
      - ./docker-volume-files/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./docker-volume-files/dashboards:/etc/grafana/dashboards
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - loki
      - prometheus
