services:
  mongodb:
    image: mongo:8.0.6
    ports:
      - '27017:27017'

  loki:
    image: grafana/loki:3.4.2
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./docker-volume-files/loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v2.55.1
    ports:
      - "9090:9090"
    volumes:
      - ./docker-volume-files/prometheus:/workspace
    command:
      - "--config.file=/workspace/prometheus.yml"
      - "--enable-feature=exemplar-storage"
    depends_on:
      - loki

  otel-collector:
    image: otel/opentelemetry-collector:0.121.0
    command:
      - "--config=/etc/otel-collector.yaml"
    volumes:
      - ./docker-volume-files/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:2.7.1
    command:
      - "--target=all"
      - "--storage.trace.backend=local"
      - "--storage.trace.local.path=/var/tempo"
      - "--auth.enabled=false"
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - ./docker-volume-files/tempo-config.yaml:/etc/tempo.yaml
    ports:
      - "14250:14250"
      - "4317"
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "3000:3000"
    volumes:
      - ./docker-volume-files/grafana/:/etc/grafana/provisioning/datasources
      - ./docker-volume-files/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./docker-volume-files/dashboards:/etc/grafana/dashboards
    environment:
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_BASIC_ENABLED: false

    depends_on:
      - loki
      - prometheus
