spring:
  application.name: Hello App
  docker:
    compose:
      lifecycle-management: start_only
  threads:
    virtual:
      enabled: true

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    baggage:
      correlation:
        fields:
          - custom_tx_id
      enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

logging:
  level:
    root: warn
    red.cliff: info

springdoc:
  swagger-ui:
    use-root-path: true
