spring:
  application.name: ${SERVICE_NAME:spring-boot-observability}
  docker:
    compose:
      lifecycle-management: start_only
      readiness:
        timeout: 30s
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      database: demo


management:
  observations:
    annotations:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0.5, 0.95, 0.99, 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
    java:
      enabled: true
  opentelemetry:
    resource-attributes:
      app: ${spring.application.name}
  tracing:
    sampling:
      probability: 1

info:
  application:
    name: ${spring.application.name}

logging:
  level:
    root: info

spring.jackson.default-property-inclusion: non_null

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    use-root-path: true

service:
  httpclient:
    httpbin:
      url: https://httpbin.org

  auth:
    token:
      validity: 1h
