### api call
GET {{uri}}/trace/api-call

### info
GET {{uri}}/trace/info

### random
GET {{uri}}/trace/random

### error
GET {{uri}}/trace/error

### error a
GET {{uri}}/trace/error-a

### error b
GET {{uri}}/trace/error-b

### error c
GET {{uri}}/trace/error-c

### suspend
GET {{uri}}/trace/suspend
