name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      checks: write
    name: Compile and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          require_tests: true
          detailed_summary: true
