name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      checks: write
    secrets: inherit

  release:
    permissions:
      packages: write
      contents: write
    name: Release
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Release
        run: |
          git config user.name "GitHub Actions"
          git config user.email "release@users.noreply.github.com"
          ./gradlew release
          git push --tags

      - name: Publish container image
        env:
          CR_USERNAME: ${{ github.actor }}
          CR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew bootBuildImage --publishImage
